### ISSUE TITLE
Update: Change "Diary" in header to "Journal"

### ISSUE THREAD

**Issue by jonpmarino** [reynalddizon/MapStoryToDo#15]
Also change reference to "Diary Entries" in profile to "Journal Entries"

**Comment by travislbrundage** [comment]
This sounds like just a wording change, so 5 minutes effort.

**Comment by jonpmarino** [comment]
Great!

**Comment by travislbrundage** [comment]
Closed by [Pull Request #28](https://github.com/MapStory/mapstory-geonode/pull/28)

**Comment by jonpmarino** [comment]
nice!
